source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNDraggableScrollBarController_Example', :exclusive => true do
  pod "NNDraggableScrollBarController", :path => "../"
end

target 'NNDraggableScrollBarController_Tests', :exclusive => true do
  pod "NNDraggableScrollBarController", :path => "../"

  
end
